name: Build apps on given SDK ref

on:
  workflow_dispatch:
    inputs:
      sdk_ref:
        type: string
        required: false
        default: 'master'
        
jobs:
  build-nanox:
    name: Build for all targets
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Setup repos
        run: | 
          python3 scripts/build_and_test/main.py --input_file input_files/input.json 

      - name: Launch build nanox
        run: | 
          python3 scripts/build_and_test/main.py --sdk_ref ${{ inputs.sdk_ref}} --input_file input_files/input.json --build --nanox --skip_setup --output_file build_nanox.json

      #- name: Push info to DB
      #  run: | 
      #    python3 scripts/push_db.py --input_file build_output.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: report.json
          path: build_nanox.json

      - name: Convert to markdown
        run: |
          python3 scripts/output_scripts/convert.py --input_file build_nanox.json --output_file out.md --key build
          cat out.md >> $GITHUB_STEP_SUMMARY

      - name: Set job status
        run: |
          python3 scripts/output_scripts/status.py --input_file build_nanox.json --key build
