name: Define targeted devices list

on:
  workflow_call:
    inputs:
      with_nanosp:
        description: Request to target Nanos+
        type: boolean
        required: false
        default: true
      with_nanox:
        description: Request to target Nanox
        type: boolean
        required: false
        default: true
      with_stax:
        description: Request to target Stax
        type: boolean
        required: false
        default: true
      with_flex:
        description: Request to target Flex
        type: boolean
        required: false
        default: true
    outputs:
      devices_config:
        description: The list of devices to build for
        value: ${{ jobs.define_devices.outputs.devices_config }}


jobs:
  define_devices:
    name: Set devices
    runs-on: ubuntu-latest
    outputs:
      devices_config: ${{ steps.devices_list.outputs.devices_config }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Define the list of devices to target
        id: devices_list
        run: |
          ARGS=(-e "${{ github.event_name}}" -o devices_config)
          if [ "${{ inputs.with_nanosp }}" = 'true' ]; then
            ARGS+=(--nanosp)
          fi
          if [ "${{ inputs.with_nanox }}" = 'true' ]; then
            ARGS+=(--nanox)
          fi
          if [ "${{ inputs.with_stax }}" = 'true' ]; then
            ARGS+=(--stax)
          fi
          if [ "${{ inputs.with_flex }}" = 'true' ]; then
            ARGS+=(--flex)
          fi
          ./scripts/setup_devices.py "${ARGS[@]}"

      - name: Print devices
        run: |
          echo "Devices: ${{ steps.devices_list.outputs.devices_config }}"
