name: Define targeted devices list

on:
  workflow_call:
    inputs:
      run_for_devices:
        description: The list of device(s) to target. Defaults to 'All'
        required: false
        default: 'All'
        type: string
    outputs:
      devices_config:
        description: The list of devices to build for
        value: ${{ jobs.define_devices.outputs.devices_config }}


jobs:
  define_devices:
    name: Set devices
    runs-on: ubuntu-latest
    outputs:
      devices_config: ${{ steps.devices_list.outputs.devices_config }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Define the list of devices to target
        id: devices_list
        shell: bash
        run: |
          if [ "${{ inputs.run_for_devices }}" = "All" ]; then
            run_for_devices=$(jq -r '.[0].devices | join (" ")' "input_files/devices_list.json")
          else
            run_for_devices="${{ inputs.run_for_devices }}"
          fi
          echo "devices_config=${run_for_devices}" >> "$GITHUB_OUTPUT"

      - name: Print devices
        run: |
          echo "Devices: ${{ steps.devices_list.outputs.devices_config }}"
