name: Test apps on given SDK ref

on:
  workflow_dispatch:
    inputs:
      sdk_ref_nanosp:
        type: string
        required: false
        default: 'API_LEVEL_1'
      run_nanosp: 
        type: boolean
        required: false
        default: true

      sdk_ref_nanox:
        type: string
        required: false
        default: 'API_LEVEL_5'
      run_nanox: 
        type: boolean
        required: false
        default: true

      sdk_ref_stax:
        type: string
        required: false
        default: 'API_LEVEL_12'
      run_stax: 
        type: boolean
        required: false
        default: true

jobs:
  split-input-file: 
    name: Split input file
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Split input into 10 files
        run: | 
          python3 scripts/split_input/split_input.py --input_file input_files/input.json 

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_1.json
          path: input_1.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_2.json
          path: input_2.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_3.json
          path: input_3.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_4.json
          path: input_4.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_5.json
          path: input_5.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_6.json
          path: input_6.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_7.json
          path: input_7.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_8.json
          path: input_8.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_9.json
          path: input_9.json

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: input_10.json
          path: input_10.json

  test-all:
    name: Test for all targets
    runs-on: ubuntu-latest
    needs: split-input-file
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest

    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Download split input file
        uses: actions/download-artifact@v3
        with:
          name: input_${{ matrix.index }}.json

      - name: Setup repos
        run: | 
          python3 scripts/build_and_test/main.py --input_file input_${{ matrix.index }}.json 

      - name: Install tests dependencies
        run: |
          apk add gmp-dev g++ openssl-dev
          pip install -U pip setuptools

      - name: Launch test nanosp
        if: ${{ inputs.run_nanosp }}
        run: | 
          python scripts/build_and_test/main.py --sdk_ref ${{ inputs.sdk_ref_nanosp }} --input_file input_${{ matrix.index }}.json --test --nanosp --skip_setup --output_file test_nanosp_${{ matrix.index }}.json

      - name: Launch test nanox
        if: ${{ inputs.run_nanox }}
        run: | 
          python scripts/build_and_test/main.py --sdk_ref ${{ inputs.sdk_ref_nanox }} --input_file input_${{ matrix.index }}.json --test --nanox --skip_setup --output_file test_nanox_${{ matrix.index }}.json

      - name: Launch test stax
        if: ${{ inputs.run_stax }}
        run: | 
          python scripts/build_and_test/main.py --sdk_ref ${{ inputs.sdk_ref_stax }} --input_file input_${{ matrix.index }}.json --test --stax --skip_setup --output_file test_stax_${{ matrix.index }}.json

      - name: Merge output files
        run: | 
          python scripts/output_scripts/merge.py --input_pattern "test_*.json" --output_file test_output_${{ matrix.index }}.json --key "test"
      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: test_output_${{ matrix.index }}.json
          path: test_output_${{ matrix.index }}.json


  info-devices:
    name: Setup test infos
    runs-on: ubuntu-latest
    needs: test-all

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_1.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_2.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_3.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_4.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_5.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_6.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_7.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_8.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_9.json

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: test_output_10.json

      - name: Merge output files
        run: | 
          python scripts/output_scripts/merge.py --input_pattern "test_output_*.json" --output_file test_output.json --key "test"

      - name: Archive output file
        uses: actions/upload-artifact@v3
        with:
          name: report.json
          path: test_output.json

      - name: Convert to markdown
        run: |
          python scripts/output_scripts/convert.py --input_file test_output.json --output_file out.md --key test
          cat out.md >> $GITHUB_STEP_SUMMARY

      - name: Convert to slack json
        run: |
          python scripts/output_scripts/slack.py --input_file test_output.json --output_file slack.json --key test

      - name: Send custom JSON data to Slack workflow
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
            payload-file-path: slack.json
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Set job status
        run: |
          python scripts/output_scripts/status.py --input_file test_output.json --key test
