name: Build apps on given SDK ref

on:
  schedule:
    - cron: '32 5 * * 1,2,3,4,5'

  pull_request:

  workflow_dispatch:
    inputs:
      sdk_ref:
        description: The SDK branch or sha1 to build against.
        type: string
        required: false
        default: 'master'
      with_nanosp:
        description: Request to target Nanos+
        type: boolean
        required: false
        default: true
      with_nanox:
        description: Request to target Nanox
        type: boolean
        required: false
        default: true
      with_stax:
        description: Request to target Stax
        type: boolean
        required: false
        default: true
      with_flex:
        description: Request to target Flex
        type: boolean
        required: false
        default: true
      with_variants:
        description: Request to build all known variants
        type: boolean
        required: false
        default: false
      send_to_slack:
        description: Request to send the result on Slack
        type: boolean
        required: false
        default: false


env:
  # Add the names of the repositories to whitelist here, separated by spaces
  # WHITELIST:
  BLACKLIST: "app-avalanche app-karura app-polkadex app-xxnetwork"
  DEFAULT_SDK: "master"


jobs:
  devices_config:
    name: Set devices
    uses: ./.github/workflows/_setup_devices.yml
    with:
      with_nanosp: ${{ inputs.with_nanosp || false }}
      with_nanox: ${{ inputs.with_nanox || false }}
      with_stax: ${{ inputs.with_stax || false }}
      with_flex: ${{ inputs.with_flex || false }}

  apps_config:
    name: Set SDK, Whitelist and Blacklist
    runs-on: ubuntu-latest
    outputs:
      whitelist: ${{ steps.get_whitelist.outputs.whitelist }}
      blacklist: ${{ steps.get_blacklist.outputs.blacklist }}
      sdk_ref: ${{ steps.get_sdk.outputs.sdk_ref }}

    steps:
      - name: Get Whitelist Apps
        id: get_whitelist
        run: |
          echo "whitelist=${{ env.WHITELIST || '' }}" >> "$GITHUB_OUTPUT"
      - name: Get Blacklist Apps
        id: get_blacklist
        run: |
          echo "blacklist=${{ env.BLACKLIST || '' }}" >> "$GITHUB_OUTPUT"

      - name: Get SDK
        id: get_sdk
        run: |
          echo "sdk_ref=${{ inputs.sdk_ref || env.DEFAULT_SDK }}" >> "$GITHUB_OUTPUT"

  execute_build:
    name: Build All apps
    needs: [devices_config, apps_config]
    uses: ./.github/workflows/_build_app.yml
    with:
      mode: "build"
      sdk_branch: ${{ needs.apps_config.outputs.sdk_ref }}
      sdk_type: "all"
      devices: ${{ needs.devices_config.outputs.devices_config }}
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}
      only_apps: ${{ needs.apps_config.outputs.whitelist }}
      with_variants: ${{ inputs.with_variants || true }}

  build_artifacts:
    name: Build Artifacts
    if: always()
    needs: [execute_build]
    uses: ./.github/workflows/_artifacts.yml
    with:
      mode: "build"

  build_status:
    name: Build Status
    if: always()
    needs: [apps_config, execute_build, build_artifacts]
    uses: ./.github/workflows/_status.yml
    with:
      mode: "build"
      job_name: "Build"
      total_apps: ${{ needs.execute_build.outputs.total_apps }}
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}
      with_variants: ${{ inputs.with_variants || true }}

  slack_message:
    name: Slack Message
    if: always()
    needs: [devices_config, execute_build, build_status]
    uses: ./.github/workflows/_slack_message.yml
    with:
      devices: ${{ needs.devices_config.outputs.devices_config }}
      total_apps: ${{ needs.execute_build.outputs.total_apps }}
      title: "Build"

  slack_notification:
    name: Slack Notification
    if: always()
    needs: [slack_message]
    runs-on: ubuntu-latest
    steps:
      - name: Download Slack Message
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: slack_message

      - name: Send custom JSON data to Slack
        if: ${{ github.event_name == 'schedule' || inputs.send_to_slack == true }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: slack.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Delete artifact
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
            name: slack_message
