name: Build All Apps on given SDK ref

on:
  schedule:
    - cron: '32 5 * * 1,2,3,4,5'

  pull_request:

  workflow_dispatch:
    inputs:
      default_all_apps:
        description: Run on All Apps (default is the predefined Whitelist & Blacklist).
        type: boolean
        required: false
        default: false
      sdk_reference:
        description: The SDK reference for the build.
        type: string
        required: false
        default: 'master'
      run_for_devices:
        description: List of device(s) to target. Defaults to 'All'
        required: false
        default: 'All'
        type: string
      with_variants:
        description: Build for all known variants.
        type: boolean
        required: false
        default: false
      send_to_slack:
        description: Send the result on Slack.
        type: boolean
        required: false
        default: false


jobs:
  devices_config:
    name: Set Devices list
    uses: ./.github/workflows/_setup_devices.yml
    with:
      run_for_devices: ${{ inputs.run_for_devices || 'All' }}

  apps_config:
    name: Set Apps lists
    uses: ./.github/workflows/_setup_apps.yml
    if: inputs.default_all_apps == false
    with:
      mode: "build"

  execute_build:
    name: Build All apps
    needs: [devices_config, apps_config]
    uses: ./.github/workflows/_build_app.yml
    with:
      mode: "build"
      sdk_reference: ${{ inputs.sdk_reference }}
      run_for_devices: ${{ needs.devices_config.outputs.devices_config }}
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}
      only_apps: ${{ needs.apps_config.outputs.whitelist }}
      with_variants: ${{ inputs.with_variants || true }}

  build_artifacts:
    name: Build Artifacts
    if: always()
    needs: [execute_build]
    uses: ./.github/workflows/_artifacts.yml
    with:
      mode: "build"

  build_status:
    name: Build Status
    if: always()
    needs: [execute_build, build_artifacts]
    uses: ./.github/workflows/_status.yml
    with:
      mode: "build"
      job_name: "Build"
      total_apps: ${{ needs.execute_build.outputs.total_apps }}

  slack_message:
    name: Slack Message
    if: always()
    needs: [devices_config, execute_build, build_status]
    uses: ./.github/workflows/_slack_message.yml
    secrets: inherit
    with:
      run_for_devices: ${{ needs.devices_config.outputs.devices_config }}
      total_apps: ${{ needs.execute_build.outputs.total_apps }}
      title: "Build"
      send_to_slack: ${{ inputs.send_to_slack || false }}
