name: Check All Apps

on:
  schedule:
    - cron: '32 5 * * 3'

  pull_request:

  workflow_dispatch:
    inputs:
      default_all_apps:
        description: Run on All Apps (default is the predefined Whitelist & Blacklist).
        type: boolean
        required: false
        default: false
      scan_device:
        description: Targeted device for scan.
        type: choice
        options:
          - nanos+
          - nanox
          - stax
          - flex
        required: false
        default: 'stax'
      send_to_slack:
        description: Send the result on Slack.
        type: boolean
        required: false
        default: false


jobs:
  device_config:
    name: Get device
    runs-on: ubuntu-latest
    outputs:
      scan_device: ${{ steps.set_device.outputs.scan_device }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set Device
        id: set_device
        run: |
          if [ "${{ inputs.scan_device }}" = "" ]; then
            scan_device=$(jq -r '.[1]["device for check"]' "input_files/devices_list.json")
          else
            scan_device="${{ inputs.scan_device }}"
          fi
          echo "scan_device=${scan_device}"
          echo "scan_device=${scan_device}" >> "$GITHUB_OUTPUT"

  apps_config:
    name: Set Apps lists
    uses: ./.github/workflows/_setup_apps.yml
    if: inputs.default_all_apps == false
    with:
      mode: "check"

  execute_check:
    name: Check All apps
    needs: [device_config, apps_config]
    uses: ./.github/workflows/_check_app.yml
    secrets: inherit
    with:
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}
      only_apps: ${{ needs.apps_config.outputs.whitelist }}
      scan_device: ${{ needs.device_config.outputs.scan_device }}

  check_artifacts:
    name: Check Artifacts
    if: always()
    needs: [execute_check]
    uses: ./.github/workflows/_artifacts.yml
    with:
      mode: "check"

  check_status:
    name: Check Status
    if: always()
    needs: [apps_config, execute_check, check_artifacts]
    uses: ./.github/workflows/_status.yml
    with:
      mode: "check"
      job_name: "Check"
      total_apps: ${{ needs.execute_check.outputs.total_apps }}

  slack_message:
    name: Slack Message
    if: always()
    needs: [execute_check, check_status]
    uses: ./.github/workflows/_slack_message.yml
    secrets: inherit
    with:
      total_apps: ${{ needs.execute_check.outputs.total_apps }}
      missing_apps: ${{ needs.check_status.outputs.missing_apps }}
      title: "Guideline Enforcer"
      send_to_slack: ${{ inputs.send_to_slack || false }}
