name: Check All Apps

on:
  schedule:
    - cron: '32 5 * * 3'

  pull_request:

  workflow_dispatch:
    inputs:
      default_all_apps:
        description: Run on All Apps (default is defined Whitelist & Blacklist).
        type: boolean
        required: false
        default: false
      send_to_slack:
        description: Request to send the result on Slack.
        type: boolean
        required: false
        default: false


env:
  # Add the names of the repositories to whitelist here, separated by spaces
  WHITELIST: "app-bitcoin app-bitcoin-new app-boilerplate app-cardano app-ethereum app-exchange app-monero app-passwords app-plugin-boilerplate app-recovery-check app-security-key app-solana app-tron app-xrp"
  # BLACKLIST:
  DEFAULT_SDK: "master"


jobs:
  apps_config:
    name: Set Whitelist and Blacklist
    runs-on: ubuntu-latest
    outputs:
      whitelist: ${{ steps.get_whitelist.outputs.whitelist }}
      blacklist: ${{ steps.get_blacklist.outputs.blacklist }}

    steps:
      - name: Get Whitelist Apps
        if: inputs.default_all_apps == false
        id: get_whitelist
        run: |
          echo "whitelist=${{ env.WHITELIST || '' }}" >> "$GITHUB_OUTPUT"
      - name: Get Blacklist Apps
        if: inputs.default_all_apps == false
        id: get_blacklist
        run: |
          echo "blacklist=${{ env.BLACKLIST || '' }}" >> "$GITHUB_OUTPUT"

  execute_check:
    name: Check All apps
    needs: [apps_config]
    uses: ./.github/workflows/_check_app.yml
    with:
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}
      only_apps: ${{ needs.apps_config.outputs.whitelist }}

  check_artifacts:
    name: Check Artifacts
    if: always()
    needs: [execute_check]
    uses: ./.github/workflows/_artifacts.yml
    with:
      mode: "check"

  check_status:
    name: Check Status
    if: always()
    needs: [apps_config, execute_check, check_artifacts]
    uses: ./.github/workflows/_status.yml
    with:
      mode: "check"
      job_name: "Check"
      total_apps: ${{ needs.execute_check.outputs.total_apps }}
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}

  slack_message:
    name: Slack Message
    if: always()
    needs: [execute_check, check_status]
    uses: ./.github/workflows/_slack_message.yml
    secrets: inherit
    with:
      total_apps: ${{ needs.execute_check.outputs.total_apps }}
      title: "Check"
      send_to_slack: ${{ inputs.send_to_slack || false }}
