name: Test All Apps on given SDK ref

on:
  schedule:
    - cron: '32 5 * * 1'

  pull_request:

  workflow_dispatch:
    inputs:
      default_all_apps:
        description: Run on All Apps (default is the predefined Whitelist & Blacklist).
        type: boolean
        required: false
        default: false
      sdk_reference:
        description: The SDK reference for the build (ATTENTION - an SDK change impacts most probably the apps snapshots).
        type: string
        required: false
        default: 'master'
      run_for_devices:
        description: List of device(s) to target. Defaults to 'All'
        required: false
        default: 'All'
        type: string
      send_to_slack:
        description: Send the result on Slack.
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      default_all_apps:
        description: Run on All Apps (default is the predefined Whitelist & Blacklist).
        type: boolean
        required: false
        default: false
      sdk_reference:
        description: The SDK reference for the build.
        type: string
        required: false
        default: 'master'
      run_for_devices:
        description: List of device(s) to target. Defaults to 'All'
        required: false
        default: 'All'
        type: string


jobs:
  devices_config:
    name: Set Devices list
    uses: ./.github/workflows/_setup_devices.yml
    with:
      run_for_devices: ${{ inputs.run_for_devices || 'All' }}

  apps_config:
    name: Set Apps lists
    uses: ./.github/workflows/_setup_apps.yml
    if: inputs.default_all_apps == false
    with:
      mode: "test"

  execute_build:
    name: Build All apps
    needs: [devices_config, apps_config]
    uses: ./.github/workflows/_build_app.yml
    secrets: inherit
    with:
      mode: "test"
      sdk_reference: ${{ inputs.sdk_reference }}
      run_for_devices: ${{ needs.devices_config.outputs.devices_config }}
      exclude_apps: ${{ needs.apps_config.outputs.blacklist }}
      only_apps: ${{ needs.apps_config.outputs.whitelist }}

  build_artifacts:
    name: Build Artifacts
    if: always()
    needs: [execute_build]
    uses: ./.github/workflows/_artifacts.yml
    with:
      mode: "build"

  execute_test:
    name: Test All apps
    if: always()
    needs: [build_artifacts]
    uses: ./.github/workflows/_test_app.yml
    secrets: inherit

  test_artifacts:
    name: Test Artifacts
    if: always()
    needs: [execute_test]
    uses: ./.github/workflows/_artifacts.yml
    with:
      mode: "test"

  test_status:
    name: Test Status
    if: always()
    needs: [execute_build, test_artifacts]
    uses: ./.github/workflows/_status.yml
    with:
      mode: "test"
      job_name: "Build"
      total_apps: ${{ needs.execute_build.outputs.total_apps }}

  slack_message:
    name: Slack Message
    if: always()
    needs: [devices_config, execute_build, test_status]
    uses: ./.github/workflows/_slack_message.yml
    secrets: inherit
    with:
      run_for_devices: ${{ needs.devices_config.outputs.devices_config }}
      total_apps: ${{ needs.execute_build.outputs.total_apps }}
      missing_apps: ${{ needs.test_status.outputs.missing_apps }}
      title: "Ragger Tests"
      send_to_slack: ${{ inputs.send_to_slack || false }}
